image_generation:
  cfg:
    height: 512
    id_length: 2
    model_name: stabilityai/stable-diffusion-xl-base-1.0
    num_turns: 3
    width: 1024
  params:
    guidance_scale: 10.0
    seed: 112536
    style_name: Storybook
  tool: story_diffusion_t2i
speech_generation:
  cfg:
    sample_rate: 16000
  params:
    voice: zh-CN-XiaoxiaoNeural
  tool: edge_tts
story_dir: generated_stories/example
story_writer:
  cfg:
    max_conv_turns: 3
    num_outline: 4
    temperature: 0.5
  params:
    main_role: 一个勇敢的小男孩
    scene: 神秘的大森林
    story_topic: 森林男孩寻宝记
  tool: qa_outline_story_writer
video_compose:
  cfg: {}
  params:
    audio_codec: mp3
    audio_sample_rate: 16000
    caption:
      color: white
      font: C:/Windows/Fonts/msyh.ttc
      fontsize: 32
      max_length: 50
    fps: 8
    height: 512
    slideshow_effect:
      bg_speech_ratio: 0.6
      fade_duration: 0.8
      move_ratio: 0.9
      music_volume: 0.5
      slide_duration: 0.4
      sound_volume: 0.6
      zoom_speed: 0.5
    story_dir: generated_stories/example
    width: 1024
  tool: slideshow_video_compose
